#!/bin/bash

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
git clone --depth=1 https://github.com/mattmc3/antidote.git ${ZDOTDIR:-~}/.antidote

# We need versions >= 3.2 to sync the clipboard between tmux and nvim
zypper -n addrepo https://download.opensuse.org/repositories/home:fsirl:SLE15-Tools/15.5/home:fsirl:SLE15-Tools.repo
zypper -n refresh
zypper -n install tmux

zypper -n install zsh
chsh -s $(which zsh)

zypper -n install rustup
rustup default stable
cargo install bob-nvim
bob sync

zypper -n install ripgrep

